### PR TITLE
Alertmanagerfile

### PR DESCRIPTION
**Pull request by sathisha84**
Hi Team,

Submitting the request for the following issue : 

Recipe for Auto-scaling-amazon-ec2-using-amazon-managed-service-for-prometheus-and-alert-manager #52

Sathish : arumusat@amazon.com

### CODE REVIEW

**Comment by sathisha84** [comment]
> Thanks a lot @sathisha84! Did you do local preview with `mkdocs`?

@mhausenblas : I did reviewed with Visual studio code, through the preview option from the respective md file. i am finding some issues with mkdocs in mac and VSCode is much more simpler, we get the same local preview as mkdocs.

**Comment by mhausenblas** [comment]
> i am finding some issues with mkdocs in mac

Maybe @tomaszwaws  can help with `mkdocs` but we need to make sure it renders locally with `mkdocs serve`.

**Comment by sathisha84** [comment]
Hi Mike, can i get @tomaszwaws - AWS alias id, i am not able to find him on Slack with this id

**Comment by sathisha84** [comment]
@mhausenblas  Hi Mike, I got fixed with mkdocs locally and i verified the file with mkdocs serve and got few lines fixed and submitted the merge request. Could you please review and approve it.

**Comment by sathisha84** [comment]
@mhausenblas - Added the Index and fixed formatting issues identified in couple of lines.

**Comment by mhausenblas** [comment]
@sathisha84 thanks and can you send in a new PR with it?

**Pull request merged**
